config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"
  
  get "tasks/:id", to:"tasks#show", as: :task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end
  private

  def task_params
  params.require(:task).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
  <%= link_to task.title, task_path(task) %>
  </li>
  <% end %>
</ul>

<%= link_to "+ Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>
<ul style="list-style:none">
<%= form_with model: @restaurant do |f| %>

  <li>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </li>

  <li>
  <%= f.label :details %>
  <%= f.text_field :details %>
  </li>
<% end %>
</ul>

<%= link_to "back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2>

<%# <%= link_to "Edit task", edit_task_path(@task) %>
<%# <%= link_to "See all tasks", task_path %>